# Generated by Django 6.0.6 on 2026-07-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('EDUCATOR', 'Educator'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], default='OWNER', max_length=20),
        ),
    ]
