# Generated by Django 6.0.6 on 2026-07-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_progress_completed_progress_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('enquiry_type', models.CharField(choices=[('GENERAL', 'General Enquiry'), ('DEMO', 'Request a Demo'), ('PRICING', 'Pricing & Plans'), ('SUPPORT', 'Technical Support'), ('PARTNERSHIP', 'Partnership')], default='GENERAL', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
