# Generated by Django 6.0.6 on 2026-07-26 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueSoonReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_soon_reminders', to='institutions.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_soon_reminders', to='institutions.student')),
            ],
            options={
                'db_table': 'activity_due_soon_reminders',
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
