# Generated by Django 6.0.6 on 2026-08-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_progress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='join_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
