# Generated by Django 6.0.6 on 2026-08-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0017_timetableslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='semester_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='semester_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
