# Generated by Django 6.0.6 on 2026-08-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0018_institution_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='LightLearn', max_length=100)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('registration_open', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('otp_max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='institutions.user')),
            ],
            options={
                'db_table': 'platform_settings',
            },
        ),
    ]
