# Generated by Django 6.0.6 on 2026-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0019_platform_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(choices=[('INSTITUTION', 'Institution'), ('COURSE', 'Course'), ('EDUCATOR', 'Educator'), ('BATCH', 'Batch'), ('STUDENT', 'Student'), ('AUTH', 'Authentication')], max_length=20),
        ),
    ]
