# Generated by Django 6.0.6 on 2026-08-03 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0020_activitylog_auth_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(choices=[('INSTITUTION', 'Institution'), ('COURSE', 'Course'), ('EDUCATOR', 'Educator'), ('BATCH', 'Batch'), ('STUDENT', 'Student'), ('AUTH', 'Authentication'), ('ANNOUNCEMENT', 'Announcement')], max_length=20),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='institutions.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='institutions.user')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='institutions.institution')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
