# Generated by Django 6.0.6 on 2026-08-04 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0021_alter_activitylog_module_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='institutions.student'),
        ),
    ]
