# Generated by Django 6.0.6 on 2026-08-04 04:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0022_complaint_institution_complaint_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_updates', models.BooleanField(default=True)),
                ('complaint_replies', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='institutions.user')),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('last_sent_year_month', models.CharField(blank=True, max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedule', to='institutions.guardian')),
            ],
            options={
                'db_table': 'report_schedules',
            },
        ),
    ]
