# Generated by Django 6.0.6 on 2026-08-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0023_notificationpreference_reportschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='due_time',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
