# Generated by Django 6.0.6 on 2026-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0024_activity_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('EXAM', 'Exam')], default='ASSIGNMENT', max_length=10),
        ),
    ]
