# Generated by Django 6.0.6 on 2026-07-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0001_initial'),
        ('institutions', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educator_profile', to='institutions.user'),
        ),
        migrations.AlterField(
            model_name='educator',
            name='edu_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='educator',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='educator',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='educator',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='educator',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='educator',
            name='photo',
            field=models.ImageField(blank=True, upload_to='educators/photos/'),
        ),
    ]
