# Generated by Django 6.0.6 on 2026-07-02 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('educators', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educators.educator')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='course.course')),
            ],
            options={
                'unique_together': {('course', 'educator')},
            },
        ),
        migrations.CreateModel(
            name='CourseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_batches', to='course.course')),
            ],
            options={
                'unique_together': {('course', 'batch')},
            },
        ),
    ]
